### ISSUE TITLE
🔷 [Epic] Remove FAKs when the user has run out of space

### ISSUE THREAD

**Issue by DavidM-D** [near/fast-auth-signer#12]
```[tasklist]
### Tasks
- [ ] https://github.com/near/fast-auth-signer/issues/13
- [ ] https://github.com/near/fast-auth-signer/issues/14
- [ ] https://github.com/near/fast-auth-signer/issues/21
- [ ] https://github.com/near/fast-auth-signer/issues/22
```
