### ISSUE TITLE
Playwright automation for BVT + integration testing.

### ISSUE THREAD

**Issue by trechriron** [near/fast-auth-signer#166]
### Description

Stand up playwright automation for Fast Auth integration and BVT testing. Will use a VM that runs tests and reports results.

```[tasklist]
### Tasks
- [ ] Utility to parse emails for link (Mailtrap).
- [ ] Utility to capture auth keys to emulate devices.
- [ ] Create account end-to-end tests.
```
