### ISSUE TITLE
Separate fast auth from near discovery

### ISSUE THREAD

**Issue by esaminu** [near/fast-auth-signer#192]
Currently, fast auth runs within near discovery and webauthn keys are stored within that scope. Fast auth needs to be separated from near discovery to support signing with FAKs so that BOS components can redirect to a signer app and the user can be prompted for their webauthn FAK in a secure domain instead of arbitrarily prompted on the same domain which could lead to phishing. 
```[tasklist]
### Tasks
- [ ] https://github.com/near/fast-auth-signer/issues/16
- [ ] https://github.com/near/fast-auth-signer/issues/17
- [ ] https://github.com/near/fast-auth-signer/issues/18
- [x] Use `WalletConnection` like class to handle interfacing with the separate fast auth wallet in an iframe through a wallet selector module near/near-discovery#336
```
