### ISSUE TITLE
🔷 [Epic] Integrate new MPC API endpoints into current flows

### ISSUE THREAD

**Issue by esaminu** [near/fast-auth-signer#26]
The new API needs to be integrated into the signer app for security purposes and for usage of the new `user_credentials` endpoint for the device management work. Documentation on the new API structure can be found in [this readme](https://github.com/near/mpc-recovery/blob/develop/README.md).

```[tasklist]
### Tasks
- [x] NEAR API JS supports remote signing
- [x] FastAuth frontend supports ID Token claiming
- [x] FastAuth frontend supports the updated `/new_account` endpoint
- [x] FastAuth frontend supports the `/sign` endpoint
```

**Comment by volovyks** [comment]
@esaminu can we close this?
