### ISSUE TITLE
UX for signing a transaction with a FastAuth Account

### ISSUE THREAD

**Issue by nall-near** [near/fast-auth-signer#31]
Design for signing a transaction with a FastAuth Account. 

This design mimics the existing Near Wallet experience, with the ability to review transaction fees and other details. Most FastAuth users will not have a clear concept of account balance or contracts at this point in their user journey.

**_In Progress_: FastAuth transaction signing should be revisited to address the specific context and use cases for signing**

### [Figma Design Link](https://www.figma.com/file/slouaDC37t0FwZZRsrjiqX/Sign-Transaction?type=design&node-id=83%3A3258&mode=design&t=QnoclDAWkVEzKJhu-1)

![Image](https://github.com/near/fast-auth-signer/assets/103140483/b7285648-a56e-49ab-a594-f967774fb752)
```[tasklist]
### Tasks
- [ ] Add error cases for signing a transaction
- [ ] Add popup for "total fees" info bubble
- [ ] Create minimal alternative more aligned with FastAuth use cases
```

**Comment by nall-near** [comment]
Updated ticket with latest design direction, mimicking the Near Wallet / full transaction details experience.
