### ISSUE TITLE
[Feature Request] Make the sign route demo ready

### ISSUE THREAD

**Issue by DavidM-D** [near/fast-auth-signer#99]
```[tasklist]
### Tasks
- [ ] Add error handling
- [ ] Improve styling for mobile
- [ ] [Work out whether we have to solve the mystery of the "two transactions" for NEARCON](https://github.com/near/fast-auth-signer/issues/97)
```
@Patrick1904 This ticket should unblock your demo

**Comment by DavidM-D** [comment]
Is this done?
